
//! Autogenerated weights for `pallet_futarchy_treasury`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_futarchy_treasury
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_futarchy_treasury.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_futarchy_treasury`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_futarchy_treasury::WeightInfo for WeightInfo<T> {
	/// Storage: `FutarchyTreasury::CoretimeQuoteAuthority` (r:1 w:0)
	/// Proof: `FutarchyTreasury::CoretimeQuoteAuthority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::BootstrapOpsFundingClosed` (r:1 w:0)
	/// Proof: `FutarchyTreasury::BootstrapOpsFundingClosed` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:12 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn fund_budget_line() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13568`
		//  Estimated: `32274`
		// Minimum execution time: 101_370_000 picoseconds.
		Weight::from_parts(111_570_000, 0)
			.saturating_add(Weight::from_parts(0, 32274))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn spend() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11362`
		//  Estimated: `26846`
		// Minimum execution time: 38_890_000 picoseconds.
		Weight::from_parts(42_170_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn open_stream() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21779`
		//  Estimated: `26846`
		// Minimum execution time: 49_980_000 picoseconds.
		Weight::from_parts(54_090_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn claim_stream() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21861`
		//  Estimated: `26846`
		// Minimum execution time: 49_800_000 picoseconds.
		Weight::from_parts(51_680_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn cancel_stream() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11444`
		//  Estimated: `26846`
		// Minimum execution time: 41_090_000 picoseconds.
		Weight::from_parts(43_860_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn issue_vit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11362`
		//  Estimated: `26846`
		// Minimum execution time: 39_390_000 picoseconds.
		Weight::from_parts(43_290_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn recover_foreign() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11362`
		//  Estimated: `26846`
		// Minimum execution time: 38_610_000 picoseconds.
		Weight::from_parts(42_070_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::CoretimeRenewalAccount` (r:1 w:0)
	/// Proof: `FutarchyTreasury::CoretimeRenewalAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:10 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_coretime_renewal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12980`
		//  Estimated: `27060`
		// Minimum execution time: 128_290_000 picoseconds.
		Weight::from_parts(136_170_000, 0)
			.saturating_add(Weight::from_parts(0, 27060))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `FutarchyTreasury::CoretimeQuoteAuthority` (r:1 w:0)
	/// Proof: `FutarchyTreasury::CoretimeQuoteAuthority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn note_coretime_quote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11577`
		//  Estimated: `26846`
		// Minimum execution time: 39_290_000 picoseconds.
		Weight::from_parts(44_290_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::CoretimeQuoteAuthority` (r:1 w:0)
	/// Proof: `FutarchyTreasury::CoretimeQuoteAuthority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:8 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn prune_coretime_quote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12735`
		//  Estimated: `26846`
		// Minimum execution time: 110_391_000 picoseconds.
		Weight::from_parts(118_230_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(15))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `FutarchyTreasury::CoretimeRenewalAccount` (r:0 w:1)
	/// Proof: `FutarchyTreasury::CoretimeRenewalAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::CoretimeQuoteAuthority` (r:0 w:1)
	/// Proof: `FutarchyTreasury::CoretimeQuoteAuthority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_coretime_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_030_000 picoseconds.
		Weight::from_parts(4_470_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn sweep_insurance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12211`
		//  Estimated: `26846`
		// Minimum execution time: 74_740_000 picoseconds.
		Weight::from_parts(79_740_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `FutarchyTreasury::CommunityDistributionArmedAt` (r:1 w:0)
	/// Proof: `FutarchyTreasury::CommunityDistributionArmedAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::CommunityDistributionRemaining` (r:1 w:1)
	/// Proof: `FutarchyTreasury::CommunityDistributionRemaining` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::CommunityScheduleCount` (r:1 w:1)
	/// Proof: `FutarchyTreasury::CommunityScheduleCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Vesting::Vesting` (r:1 w:1)
	/// Proof: `Vesting::Vesting` (`max_values`: None, `max_size`: Some(337), added: 2812, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_community_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `633`
		//  Estimated: `6196`
		// Minimum execution time: 72_581_000 picoseconds.
		Weight::from_parts(77_300_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::DeadMan` (r:1 w:0)
	/// Proof: `Epoch::DeadMan` (`max_values`: Some(1), `max_size`: Some(10), added: 505, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::CollatorAuthoredEpoch` (r:1 w:1)
	/// Proof: `FutarchyTreasury::CollatorAuthoredEpoch` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::CollatorPendingEpoch` (r:1 w:1)
	/// Proof: `FutarchyTreasury::CollatorPendingEpoch` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::CollatorAuthoredBlocks` (r:1 w:1)
	/// Proof: `FutarchyTreasury::CollatorAuthoredBlocks` (`max_values`: Some(1), `max_size`: Some(4322), added: 4817, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::CollatorAuthoredRegisteredCount` (r:1 w:1)
	/// Proof: `FutarchyTreasury::CollatorAuthoredRegisteredCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Session::Validators` (r:1 w:0)
	/// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `FutarchyTreasury::CollatorPendingRegisteredCount` (r:0 w:1)
	/// Proof: `FutarchyTreasury::CollatorPendingRegisteredCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::CollatorPendingBlocks` (r:0 w:1)
	/// Proof: `FutarchyTreasury::CollatorPendingBlocks` (`max_values`: Some(1), `max_size`: Some(4322), added: 4817, mode: `MaxEncodedLen`)
	fn note_collator_block() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4805`
		//  Estimated: `6290`
		// Minimum execution time: 17_540_000 picoseconds.
		Weight::from_parts(19_010_000, 0)
			.saturating_add(Weight::from_parts(0, 6290))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
	}
}
