
//! Autogenerated weights for `pallet_conditional_ledger`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-07-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_conditional_ledger
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_conditional_ledger.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_conditional_ledger`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_conditional_ledger::WeightInfo for WeightInfo<T> {
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn split() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1681`
		//  Estimated: `36928`
		// Minimum execution time: 198_830_000 picoseconds.
		Weight::from_parts(199_960_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(37))
			.saturating_add(T::DbWeight::get().writes(35))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn merge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2046`
		//  Estimated: `36928`
		// Minimum execution time: 206_510_000 picoseconds.
		Weight::from_parts(208_781_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn split_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2201`
		//  Estimated: `36928`
		// Minimum execution time: 183_190_000 picoseconds.
		Weight::from_parts(184_980_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(36))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn merge_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2196`
		//  Estimated: `36928`
		// Minimum execution time: 188_330_000 picoseconds.
		Weight::from_parts(191_960_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn split_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2201`
		//  Estimated: `36928`
		// Minimum execution time: 182_200_000 picoseconds.
		Weight::from_parts(185_540_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(36))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn merge_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2194`
		//  Estimated: `36928`
		// Minimum execution time: 185_320_000 picoseconds.
		Weight::from_parts(192_230_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::Positions` (r:28 w:28)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2273`
		//  Estimated: `72866`
		// Minimum execution time: 289_260_000 picoseconds.
		Weight::from_parts(296_130_000, 0)
			.saturating_add(Weight::from_parts(0, 72866))
			.saturating_add(T::DbWeight::get().reads(52))
			.saturating_add(T::DbWeight::get().writes(49))
	}
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn split_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1560`
		//  Estimated: `6208`
		// Minimum execution time: 106_271_000 picoseconds.
		Weight::from_parts(107_900_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn merge_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1909`
		//  Estimated: `6208`
		// Minimum execution time: 114_190_000 picoseconds.
		Weight::from_parts(115_370_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn resolve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `464`
		//  Estimated: `36256`
		// Minimum execution time: 61_570_000 picoseconds.
		Weight::from_parts(62_140_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(15))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::VaultTerminalAt` (r:0 w:1)
	/// Proof: `ConditionalLedger::VaultTerminalAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn void() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `464`
		//  Estimated: `36256`
		// Minimum execution time: 63_170_000 picoseconds.
		Weight::from_parts(64_170_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::VaultTerminalAt` (r:0 w:1)
	/// Proof: `ConditionalLedger::VaultTerminalAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn settle_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `465`
		//  Estimated: `36256`
		// Minimum execution time: 64_470_000 picoseconds.
		Weight::from_parts(65_850_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn settle_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `465`
		//  Estimated: `36256`
		// Minimum execution time: 62_590_000 picoseconds.
		Weight::from_parts(63_580_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(15))
	}
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineTerminalAt` (r:0 w:1)
	/// Proof: `ConditionalLedger::BaselineTerminalAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn settle_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `337`
		//  Estimated: `6028`
		// Minimum execution time: 23_750_000 picoseconds.
		Weight::from_parts(24_310_000, 0)
			.saturating_add(Weight::from_parts(0, 6028))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn redeem() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2089`
		//  Estimated: `36928`
		// Minimum execution time: 207_320_000 picoseconds.
		Weight::from_parts(209_540_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn redeem_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2239`
		//  Estimated: `36928`
		// Minimum execution time: 211_710_000 picoseconds.
		Weight::from_parts(216_670_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn redeem_scalar_pair() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2239`
		//  Estimated: `36928`
		// Minimum execution time: 216_960_000 picoseconds.
		Weight::from_parts(219_540_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn redeem_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2238`
		//  Estimated: `36928`
		// Minimum execution time: 215_450_000 picoseconds.
		Weight::from_parts(218_780_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn redeem_void() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2080`
		//  Estimated: `36928`
		// Minimum execution time: 210_760_000 picoseconds.
		Weight::from_parts(213_630_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn redeem_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1929`
		//  Estimated: `6208`
		// Minimum execution time: 114_590_000 picoseconds.
		Weight::from_parts(118_270_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn redeem_baseline_pair() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1929`
		//  Estimated: `6208`
		// Minimum execution time: 114_790_000 picoseconds.
		Weight::from_parts(115_830_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `ConditionalLedger::VaultTerminalAt` (r:1 w:1)
	/// Proof: `ConditionalLedger::VaultTerminalAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:114 w:100)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:50 w:50)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:51 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:52 w:52)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	fn sweep_dust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19497`
		//  Estimated: `293628`
		// Minimum execution time: 5_141_614_000 picoseconds.
		Weight::from_parts(5_237_002_000, 0)
			.saturating_add(Weight::from_parts(0, 293628))
			.saturating_add(T::DbWeight::get().reads(275))
			.saturating_add(T::DbWeight::get().writes(209))
	}
	/// Storage: `ConditionalLedger::BaselineTerminalAt` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineTerminalAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:102 w:100)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:50 w:50)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:51 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:52 w:52)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	fn sweep_dust_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19213`
		//  Estimated: `262824`
		// Minimum execution time: 4_608_562_000 picoseconds.
		Weight::from_parts(4_664_223_000, 0)
			.saturating_add(Weight::from_parts(0, 262824))
			.saturating_add(T::DbWeight::get().reads(263))
			.saturating_add(T::DbWeight::get().writes(209))
	}
}
