
//! Autogenerated weights for `pallet_market`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-07-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_market
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_market.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_market`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_market::WeightInfo for WeightInfo<T> {
	/// Storage: `Market::Markets` (r:1 w:1)
	/// Proof: `Market::Markets` (`max_values`: None, `max_size`: Some(213), added: 2688, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:42 w:42)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:3 w:3)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:4 w:4)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3480`
		//  Estimated: `108804`
		// Minimum execution time: 1_198_041_000 picoseconds.
		Weight::from_parts(1_213_840_000, 0)
			.saturating_add(Weight::from_parts(0, 108804))
			.saturating_add(T::DbWeight::get().reads(71))
			.saturating_add(T::DbWeight::get().writes(67))
	}
	/// Storage: `Market::Markets` (r:1 w:1)
	/// Proof: `Market::Markets` (`max_values`: None, `max_size`: Some(213), added: 2688, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:42 w:42)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:3 w:3)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3891`
		//  Estimated: `108804`
		// Minimum execution time: 967_070_000 picoseconds.
		Weight::from_parts(978_421_000, 0)
			.saturating_add(Weight::from_parts(0, 108804))
			.saturating_add(T::DbWeight::get().reads(70))
			.saturating_add(T::DbWeight::get().writes(66))
	}
	/// Storage: `Market::Markets` (r:1 w:1)
	/// Proof: `Market::Markets` (`max_values`: None, `max_size`: Some(213), added: 2688, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn crank_observe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1739`
		//  Estimated: `8799`
		// Minimum execution time: 27_090_000 picoseconds.
		Weight::from_parts(27_580_000, 0)
			.saturating_add(Weight::from_parts(0, 8799))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Market::Markets` (r:1 w:1)
	/// Proof: `Market::Markets` (`max_values`: None, `max_size`: Some(213), added: 2688, mode: `MaxEncodedLen`)
	/// Storage: `Market::ClosedAt` (r:1 w:1)
	/// Proof: `Market::ClosedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Market::CounterForMarkets` (r:1 w:1)
	/// Proof: `Market::CounterForMarkets` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Market::SeededMarkets` (r:0 w:1)
	/// Proof: `Market::SeededMarkets` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn reap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1317`
		//  Estimated: `3678`
		// Minimum execution time: 25_240_000 picoseconds.
		Weight::from_parts(25_640_000, 0)
			.saturating_add(Weight::from_parts(0, 3678))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Market::Markets` (r:1 w:1)
	/// Proof: `Market::Markets` (`max_values`: None, `max_size`: Some(213), added: 2688, mode: `MaxEncodedLen`)
	/// Storage: `Market::CounterForMarkets` (r:1 w:1)
	/// Proof: `Market::CounterForMarkets` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	fn create_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `3678`
		// Minimum execution time: 15_800_000 picoseconds.
		Weight::from_parts(16_100_000, 0)
			.saturating_add(Weight::from_parts(0, 3678))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Market::Markets` (r:1 w:0)
	/// Proof: `Market::Markets` (`max_values`: None, `max_size`: Some(213), added: 2688, mode: `MaxEncodedLen`)
	/// Storage: `Market::SeededMarkets` (r:1 w:1)
	/// Proof: `Market::SeededMarkets` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:28 w:28)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn seed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1977`
		//  Estimated: `72866`
		// Minimum execution time: 552_840_000 picoseconds.
		Weight::from_parts(572_150_000, 0)
			.saturating_add(Weight::from_parts(0, 72866))
			.saturating_add(T::DbWeight::get().reads(54))
			.saturating_add(T::DbWeight::get().writes(52))
	}
	/// Storage: `Market::Markets` (r:1 w:1)
	/// Proof: `Market::Markets` (`max_values`: None, `max_size`: Some(213), added: 2688, mode: `MaxEncodedLen`)
	/// Storage: `Market::ClosedAt` (r:0 w:1)
	/// Proof: `Market::ClosedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `373`
		//  Estimated: `3678`
		// Minimum execution time: 10_430_000 picoseconds.
		Weight::from_parts(10_780_000, 0)
			.saturating_add(Weight::from_parts(0, 3678))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Market::Markets` (r:2 w:0)
	/// Proof: `Market::Markets` (`max_values`: None, `max_size`: Some(213), added: 2688, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:0)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Market::CounterForMarkets` (r:1 w:0)
	/// Proof: `Market::CounterForMarkets` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Market::BaselineMarketOf` (r:1 w:0)
	/// Proof: `Market::BaselineMarketOf` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn try_state() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `697`
		//  Estimated: `6366`
		// Minimum execution time: 17_150_000 picoseconds.
		Weight::from_parts(17_630_000, 0)
			.saturating_add(Weight::from_parts(0, 6366))
			.saturating_add(T::DbWeight::get().reads(5))
	}
}
