
//! Autogenerated weights for `pallet_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-07-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_registry
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_registry.rs
// --unsafe-overwrite-results

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_registry`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_registry::WeightInfo for WeightInfo<T> {
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::CohortSchedules` (r:1 w:0)
	/// Proof: `Epoch::CohortSchedules` (`max_values`: None, `max_size`: Some(87), added: 2562, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:64 w:1)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn file() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10252`
		//  Estimated: `171934`
		// Minimum execution time: 325_980_000 picoseconds.
		Weight::from_parts(329_981_000, 0)
			.saturating_add(Weight::from_parts(0, 171934))
			.saturating_add(T::DbWeight::get().reads(82))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `IncidentRegistry::Filings` (r:65 w:1)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn challenge_filing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10172`
		//  Estimated: `174605`
		// Minimum execution time: 323_760_000 picoseconds.
		Weight::from_parts(330_850_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(80))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `Oracle::Watchtowers` (r:1 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::AckRecords` (r:1 w:1)
	/// Proof: `IncidentRegistry::AckRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:1)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn ack_observed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9839`
		//  Estimated: `174605`
		// Minimum execution time: 292_950_000 picoseconds.
		Weight::from_parts(297_810_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(79))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:20)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn crank_close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10120`
		//  Estimated: `174605`
		// Minimum execution time: 865_980_000 picoseconds.
		Weight::from_parts(885_101_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(80))
			.saturating_add(T::DbWeight::get().writes(31))
	}
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:1)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn resolve_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10287`
		//  Estimated: `174605`
		// Minimum execution time: 352_240_000 picoseconds.
		Weight::from_parts(359_490_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(82))
			.saturating_add(T::DbWeight::get().writes(14))
	}
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::CohortSchedules` (r:1 w:0)
	/// Proof: `Epoch::CohortSchedules` (`max_values`: None, `max_size`: Some(87), added: 2562, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:0)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:4 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::ClosedAt` (r:0 w:1)
	/// Proof: `IncidentRegistry::ClosedAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn close_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9370`
		//  Estimated: `174605`
		// Minimum execution time: 295_160_000 picoseconds.
		Weight::from_parts(299_490_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(79))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `IncidentRegistry::ClosedAt` (r:1 w:1)
	/// Proof: `IncidentRegistry::ClosedAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:64)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:4 w:3)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::AckRecords` (r:128 w:128)
	/// Proof: `IncidentRegistry::AckRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn reap_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `17779`
		//  Estimated: `329054`
		// Minimum execution time: 499_100_000 picoseconds.
		Weight::from_parts(508_970_000, 0)
			.saturating_add(Weight::from_parts(0, 329054))
			.saturating_add(T::DbWeight::get().reads(206))
			.saturating_add(T::DbWeight::get().writes(200))
	}
}
