
//! Autogenerated weights for `pallet_futarchy_treasury`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-07-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_futarchy_treasury
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_futarchy_treasury.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_futarchy_treasury`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_futarchy_treasury::WeightInfo for WeightInfo<T> {
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25259), added: 25754, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn fund_budget_line() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11039`
		//  Estimated: `26744`
		// Minimum execution time: 39_390_000 picoseconds.
		Weight::from_parts(43_400_000, 0)
			.saturating_add(Weight::from_parts(0, 26744))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25259), added: 25754, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn spend() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11039`
		//  Estimated: `26744`
		// Minimum execution time: 40_100_000 picoseconds.
		Weight::from_parts(42_640_000, 0)
			.saturating_add(Weight::from_parts(0, 26744))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25259), added: 25754, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn open_stream() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21456`
		//  Estimated: `26744`
		// Minimum execution time: 50_221_000 picoseconds.
		Weight::from_parts(50_920_000, 0)
			.saturating_add(Weight::from_parts(0, 26744))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25259), added: 25754, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_stream() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21538`
		//  Estimated: `26744`
		// Minimum execution time: 47_560_000 picoseconds.
		Weight::from_parts(48_620_000, 0)
			.saturating_add(Weight::from_parts(0, 26744))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25259), added: 25754, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn cancel_stream() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11121`
		//  Estimated: `26744`
		// Minimum execution time: 39_420_000 picoseconds.
		Weight::from_parts(41_530_000, 0)
			.saturating_add(Weight::from_parts(0, 26744))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25259), added: 25754, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn issue_vit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11039`
		//  Estimated: `26744`
		// Minimum execution time: 40_250_000 picoseconds.
		Weight::from_parts(42_840_000, 0)
			.saturating_add(Weight::from_parts(0, 26744))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25259), added: 25754, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn recover_foreign() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11039`
		//  Estimated: `26744`
		// Minimum execution time: 37_810_000 picoseconds.
		Weight::from_parts(39_370_000, 0)
			.saturating_add(Weight::from_parts(0, 26744))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25259), added: 25754, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_coretime_renewal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11087`
		//  Estimated: `26744`
		// Minimum execution time: 39_370_000 picoseconds.
		Weight::from_parts(41_421_000, 0)
			.saturating_add(Weight::from_parts(0, 26744))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
